name: Fix prettier

on:
  workflow_dispatch:
  push:

jobs:
  prettier:
    # enable manual run - and automatic fix in the JabRef organization
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.repository_owner == 'JabRef')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Runs prettier, commits and pushes if anything changed.
      # See https://github.com/creyD/prettier_action/ for details.
      - name: Prettify code
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --write **/*.{java}
          prettier_plugins: prettier-java
